- hosts: docker

  tasks:

    - name: "Configuring yum for the docker"
      yum_repository:
              name: docker
              file: docker
              description: Configure the Docker Community Edition repo
              baseurl: https://download.docker.com/linux/centos/7/x86_64/stable/
              gpgcheck: no
      register: docker_yum_status


    - name: "Docker Yum Cofiguration"
      debug:
      msg: "is the Docker Yum Configured  -> {{  docker_yum_status.failed }}"

    - name: "Installing Docker ....."
      package:
        name: "docker-ce-18.09.1-3.el7.x86_64"
        state: present
      register: installation_status     

    - name: "Installation Status"
      debug:
              msg: "Docker Installation Code  -> {{ installation_status.rc }}"

    - name: "Starting the Docker Services"
      service:
              name: docker
              state: started
              enabled: yes
      register: service_status

    - name: "Service Status"
      debug:
              msg: "Docker Service Code -> {{ service_status.state }}"

    - name: "Creating an User name deploybot who have power to completely control the Docker service"
      user:
          name: fideloper
          password: password
          groups:
          - docker
          state: present
          shell: /bin/bash
          system: no 
          createhome: yes    
          home: /home/deploybot